/// Command-line argument definitions for pgcli-rs.
///
/// Implements full `psql` flag compatibility plus pgcli-rs extensions.
/// Extensions are clearly marked with `[pgcli-rs extension]` in help text.
use clap::Parser;
use std::path::PathBuf;

/// pgcli - a self-contained PostgreSQL CLI client.
///
/// Accepts the same flags as `psql` plus additional extensions for TLS,
/// output formats, and export capabilities.
#[derive(Debug, Clone, Parser)]
#[command(
    name = "pgcli",
    version,
    about = "A self-contained PostgreSQL CLI client - no libpq required",
    long_about = None,
    disable_help_flag = true
)]
pub struct CliArgs {
    // -------------------------------------------------------------------------
    // Connection options (psql compatible)
    // -------------------------------------------------------------------------
    /// Database server host or socket directory.
    #[arg(short = 'h', long, env = "PGHOST", value_name = "HOST")]
    pub host: Option<String>,

    /// Database server port.
    #[arg(short = 'p', long, env = "PGPORT", value_name = "PORT")]
    pub port: Option<u16>,

    /// Connect as this database user.
    #[arg(short = 'U', long, env = "PGUSER", value_name = "USERNAME")]
    pub username: Option<String>,

    /// Database name to connect to.
    #[arg(short = 'd', long, env = "PGDATABASE", value_name = "DBNAME")]
    pub dbname: Option<String>,

    /// Force a password prompt.
    #[arg(short = 'W', long)]
    pub password: bool,

    /// Never prompt for password.
    #[arg(short = 'w', long)]
    pub no_password: bool,

    // -------------------------------------------------------------------------
    // Input / execution options (psql compatible)
    // -------------------------------------------------------------------------
    /// Execute a single command string, then exit.
    #[arg(short = 'c', long, value_name = "COMMAND")]
    pub command: Option<String>,

    /// Execute SQL commands from this file, then exit.
    #[arg(short = 'f', long, value_name = "FILE")]
    pub file: Option<PathBuf>,

    /// Send query output to this file instead of stdout.
    #[arg(short = 'o', long, value_name = "FILE")]
    pub output: Option<PathBuf>,

    /// Field separator for unaligned output mode.
    #[arg(short = 'F', long, default_value = "|", value_name = "SEP")]
    pub field_separator: String,

    /// Record separator for unaligned output mode.
    #[arg(short = 'R', long, default_value = "\n", value_name = "SEP")]
    pub record_separator: String,

    /// Print rows only, no column headers or row count footer.
    #[arg(short = 't', long)]
    pub tuples_only: bool,

    /// Unaligned output mode.
    #[arg(short = 'A', long)]
    pub no_align: bool,

    /// HTML table output mode.
    #[arg(short = 'H', long)]
    pub html: bool,

    /// List available databases, then exit.
    #[arg(short = 'l', long)]
    pub list: bool,

    /// Set a psql variable (`NAME=VALUE`).
    #[arg(short = 'v', long = "set", value_name = "VAR=VALUE", action = clap::ArgAction::Append)]
    pub set: Vec<String>,

    /// Do not read the startup file (`~/.psqlrc` / `~/.pgcli-rs.toml`).
    #[arg(short = 'X', long)]
    pub no_psqlrc: bool,

    /// Execute `-f` file as a single transaction.
    #[arg(short = '1', long)]
    pub single_transaction: bool,

    /// Echo failed SQL commands to stderr.
    #[arg(short = 'b', long)]
    pub echo_errors: bool,

    /// Echo all SQL commands before executing them.
    #[arg(short = 'e', long)]
    pub echo_queries: bool,

    /// Display queries generated by meta-commands.
    #[arg(short = 'E', long)]
    pub echo_hidden: bool,

    /// Log the entire session to this file.
    #[arg(short = 'L', long, value_name = "FILE")]
    pub log_file: Option<PathBuf>,

    /// Disable readline (rustyline) for input.
    #[arg(short = 'n', long)]
    pub no_readline: bool,

    /// Set a print option (`NAME[=VALUE]`).
    #[arg(short = 'P', long = "pset", value_name = "VAR[=VALUE]", action = clap::ArgAction::Append)]
    pub pset: Vec<String>,

    /// Run quietly - suppress all informational messages.
    #[arg(short = 'q', long)]
    pub quiet: bool,

    /// Single-step mode: confirm before executing each statement.
    #[arg(short = 's', long)]
    pub single_step: bool,

    /// Single-line mode: newline terminates a statement (no `;` needed).
    #[arg(short = 'S', long)]
    pub single_line: bool,

    // -------------------------------------------------------------------------
    // pgcli-rs TLS extensions
    // -------------------------------------------------------------------------
    /// [pgcli-rs extension] Disable TLS entirely (insecure, for local dev).
    #[arg(long)]
    pub no_tls: bool,

    /// [pgcli-rs extension] Require TLS; fail if server does not support it.
    #[arg(long)]
    pub require_tls: bool,

    /// [pgcli-rs extension] Client certificate file for mutual TLS.
    #[arg(long, value_name = "FILE")]
    pub tls_cert: Option<PathBuf>,

    /// [pgcli-rs extension] Client private key file for mutual TLS.
    #[arg(long, value_name = "FILE")]
    pub tls_key: Option<PathBuf>,

    /// [pgcli-rs extension] CA certificate file for server verification.
    #[arg(long, value_name = "FILE")]
    pub tls_ca: Option<PathBuf>,

    // -------------------------------------------------------------------------
    // pgcli-rs output extensions
    // -------------------------------------------------------------------------
    /// [pgcli-rs extension] Output format: table|csv|json|jsonl|tsv.
    #[arg(long, default_value = "table", value_name = "FORMAT")]
    pub format: String,

    /// [pgcli-rs extension] Export query result to file (format inferred from extension).
    #[arg(long, value_name = "FILE")]
    pub export: Option<PathBuf>,

    // -------------------------------------------------------------------------
    // pgcli-rs behaviour extensions
    // -------------------------------------------------------------------------
    /// [pgcli-rs extension] Connection and query timeout in seconds.
    #[arg(long, default_value = "30", value_name = "SECS")]
    pub timeout: u64,

    /// [pgcli-rs extension] Limit result rows displayed in interactive mode.
    #[arg(long, default_value = "1000", value_name = "N")]
    pub max_rows: usize,

    /// [pgcli-rs extension] Override pager command.
    #[arg(long, env = "PAGER", value_name = "CMD")]
    pub pager: Option<String>,

    /// [pgcli-rs extension] Disable the pager entirely.
    #[arg(long)]
    pub no_pager: bool,

    /// [pgcli-rs extension] Enable SQL syntax highlighting in REPL.
    #[arg(long, default_value = "true", value_name = "BOOL")]
    pub syntax_highlight: bool,

    /// [pgcli-rs extension] Color theme for the REPL: dark|light|none.
    #[arg(long, default_value = "dark", value_name = "THEME")]
    pub theme: String,

    /// [pgcli-rs extension] Override history file path.
    #[arg(long, value_name = "FILE")]
    pub history_file: Option<PathBuf>,

    /// [pgcli-rs extension] Load a specific config file.
    #[arg(long, value_name = "FILE")]
    pub config: Option<PathBuf>,

    // -------------------------------------------------------------------------
    // Positional: psql accepts `psql [DBNAME]` or a full connection URI
    // -------------------------------------------------------------------------
    /// Database name or `postgresql://` connection URI.
    #[arg(value_name = "DBNAME")]
    pub positional_dbname: Option<String>,

    // -------------------------------------------------------------------------
    // pgcli-rs profiling / benchmark extensions
    // -------------------------------------------------------------------------
    /// [pgcli-rs extension] Repeat --command N times; print latency histogram.
    #[arg(long, value_name = "N", default_value = "1")]
    pub repeat: u32,

    /// [pgcli-rs extension] Print throughput stats (rows/sec, bytes, p95/p99 latency).
    #[arg(long)]
    pub stats: bool,

    /// Print help information.
    #[arg(long, action = clap::ArgAction::Help)]
    pub help: Option<bool>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;

    #[test]
    fn parse_minimal_no_args() {
        let args = CliArgs::parse_from(["pgcli-rs"]);
        assert!(args.host.is_none());
        assert_eq!(args.port, None);
        assert!(!args.list);
    }

    #[test]
    fn parse_host_and_port() {
        let args = CliArgs::parse_from(["pgcli-rs", "-h", "db.example.com", "-p", "5433"]);
        assert_eq!(args.host.as_deref(), Some("db.example.com"));
        assert_eq!(args.port, Some(5433));
    }

    #[test]
    fn parse_connection_uri_positional() {
        let args = CliArgs::parse_from(["pgcli-rs", "postgresql://user:pass@localhost/mydb"]);
        assert_eq!(
            args.positional_dbname.as_deref(),
            Some("postgresql://user:pass@localhost/mydb")
        );
    }

    #[test]
    fn parse_command_flag() {
        let args = CliArgs::parse_from(["pgcli-rs", "-c", "SELECT 1"]);
        assert_eq!(args.command.as_deref(), Some("SELECT 1"));
    }

    #[test]
    fn parse_format_flag() {
        let args = CliArgs::parse_from(["pgcli-rs", "--format", "json"]);
        assert_eq!(args.format, "json");
    }
}
